# Generated by Django 3.2 on 2021-04-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expensas',
            new_name='Expense',
        ),
    ]
