# Generated by Django 3.2 on 2021-04-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_rename_expensas_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expensas_puras',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expensas Puras'),
        ),
    ]
