# Generated by Django 3.2 on 2021-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefono')),
                ('email', models.EmailField(default='No tiene', max_length=254)),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
            },
        ),
    ]
