# Generated by Django 3.2 on 2021-04-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefono')),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.apartament', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
            },
        ),
    ]
