# Generated by Django 3.2 on 2021-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeowners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeowner',
            name='email',
            field=models.EmailField(blank=True, default='No tiene', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='homeowner',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono'),
        ),
    ]
