# Generated by Django 3.2 on 2021-04-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeowners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='email',
            field=models.EmailField(default='No tiene', max_length=254),
        ),
    ]
